version: 2.1

executors:
  my-executor:
    machine:
      resource_class: imlogang-organization/machine-runner-test

jobs:
  job1:
    executor: my-executor
    steps:
      - run: echo "Job 1 completed"

workflows:
  build:
    jobs:
      - job1

